import React, { useEffect, useRef, useState } from 'react';
import { getFintuttoSDK } from '@/lib/fintutto-sdk';

/**
 * Sovendus Integration Component
 * Integrates Sovendus voucher/coupon network for post-transaction affiliate offers.
 *
 * Sovendus shows relevant vouchers from partner brands after successful user actions
 * (e.g., subscription checkout, payment completed).
 *
 * Revenue: CPC/CPL commission per user interaction with voucher offers.
 *
 * Postback-URL (im Sovendus Dashboard hinterlegen):
 *   https://aaefocdqgdgexkcrjhks.supabase.co/functions/v1/sovendusPostback
 *
 * Usage:
 *   <SovendusIntegration
 *     appId="mieterapp"
 *     trafficSourceNumber="YOUR_TRAFFIC_SOURCE"
 *     trafficMediumNumber="YOUR_TRAFFIC_MEDIUM"
 *     userEmail={user.email}
 *     orderId={orderId}
 *     orderValue={orderValue}
 *     trigger="checkout_success"
 *   />
 */

// Sovendus Traffic Source/Medium IDs (configured per Sovendus contract)
const SOVENDUS_CONFIG = {
  trafficSourceNumber: import.meta.env.VITE_SOVENDUS_TRAFFIC_SOURCE || 'FINTUTTO_SOURCE',
  trafficMediumNumber: import.meta.env.VITE_SOVENDUS_TRAFFIC_MEDIUM || 'FINTUTTO_MEDIUM',
  iframeContainerId: 'sovendus-integration-container',
  postbackUrl: 'https://aaefocdqgdgexkcrjhks.supabase.co/functions/v1/sovendusPostback',
};

export default function SovendusIntegration({
  appId = 'mieterapp',
  trafficSourceNumber = SOVENDUS_CONFIG.trafficSourceNumber,
  trafficMediumNumber = SOVENDUS_CONFIG.trafficMediumNumber,
  userEmail = '',
  orderId = '',
  orderValue = 0,
  orderCurrency = 'EUR',
  trigger = 'generic',
  consumerSalutation = '',
  consumerFirstName = '',
  consumerLastName = '',
  consumerCountry = 'DE',
  onVoucherClick,
  onClose,
}) {
  const containerRef = useRef(null);
  const [isLoaded, setIsLoaded] = useState(false);
  const [hasConsent, setHasConsent] = useState(false);
  const sdkRef = useRef(getFintuttoSDK(appId));

  // Check for existing consent
  useEffect(() => {
    const consent = localStorage.getItem('sovendus_consent');
    if (consent === 'true') {
      setHasConsent(true);
    }
  }, []);

  // Load Sovendus script when consent is given
  useEffect(() => {
    if (!hasConsent) return;

    // Set up Sovendus global configuration
    window.sovIframes = window.sovIframes || [];
    window.sovIframes.push({
      trafficSourceNumber: trafficSourceNumber,
      trafficMediumNumber: trafficMediumNumber,
      sessionId: '', // Auto-generated by Sovendus
      timestamp: Math.floor(Date.now() / 1000),
      orderId: orderId,
      orderValue: orderValue,
      orderCurrency: orderCurrency,
      usedCouponCode: '',
      iframeContainerId: SOVENDUS_CONFIG.iframeContainerId,
    });

    // Set consumer data (hashed for privacy)
    window.sovConsumer = {
      consumerSalutation: consumerSalutation,
      consumerFirstName: consumerFirstName,
      consumerLastName: consumerLastName,
      consumerEmail: userEmail,
      consumerCountry: consumerCountry,
    };

    // Load Sovendus script
    const script = document.createElement('script');
    script.type = 'text/javascript';
    script.async = true;
    script.src = 'https://api.sovendus.com/sovabo/common/js/flexibleIframe.js';
    script.onload = () => setIsLoaded(true);
    document.body.appendChild(script);

    // Track impression via Fintutto SDK (-> Supabase Edge Function)
    trackSovendusEvent('impression', { trigger, orderId, orderValue });

    return () => {
      if (document.body.contains(script)) {
        document.body.removeChild(script);
      }
      delete window.sovIframes;
      delete window.sovConsumer;
    };
  }, [hasConsent, trafficSourceNumber, trafficMediumNumber, orderId, orderValue, userEmail]);

  const trackSovendusEvent = async (eventType, data = {}) => {
    try {
      await sdkRef.current.trackSovendusEvent({
        eventType,
        trigger: data.trigger || trigger,
        orderId: data.orderId || orderId,
        orderValue: data.orderValue || orderValue,
        partnerName: data.partnerName,
        voucherCode: data.voucherCode,
      });
    } catch (e) {
      console.error('Sovendus tracking error:', e);
    }
  };

  const handleConsent = () => {
    localStorage.setItem('sovendus_consent', 'true');
    setHasConsent(true);
    trackSovendusEvent('consent_given', { trigger });
  };

  const handleDecline = () => {
    localStorage.setItem('sovendus_consent', 'false');
    onClose?.();
  };

  // Consent banner if not yet given
  if (!hasConsent) {
    return (
      <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6 max-w-lg mx-auto">
        <div className="flex items-start gap-4">
          <div className="w-12 h-12 bg-green-100 dark:bg-green-900/30 rounded-xl flex items-center justify-center flex-shrink-0">
            <span className="text-2xl" role="img" aria-label="Geschenk">&#x1F381;</span>
          </div>
          <div>
            <h3 className="font-semibold text-gray-900 dark:text-white text-lg mb-1">
              Exklusive Verguenstigungen
            </h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm mb-4">
              Erhalte attraktive Gutscheine und Rabatte von ausgewaehlten Partnern.
              Dafuer werden anonymisierte Daten an unseren Partner Sovendus uebermittelt.
              <a href="/Datenschutz" className="text-blue-600 hover:underline ml-1">Mehr erfahren</a>
            </p>
            <div className="flex gap-3">
              <button
                onClick={handleConsent}
                className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg text-sm font-medium transition-colors"
              >
                Verguenstigungen anzeigen
              </button>
              <button
                onClick={handleDecline}
                className="px-4 py-2 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-300 rounded-lg text-sm font-medium transition-colors"
              >
                Nein, danke
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="sovendus-wrapper">
      <div
        id={SOVENDUS_CONFIG.iframeContainerId}
        ref={containerRef}
        className="w-full min-h-[300px] rounded-xl overflow-hidden"
      />
      {!isLoaded && (
        <div className="flex items-center justify-center py-8">
          <div className="w-6 h-6 border-2 border-gray-200 border-t-green-600 rounded-full animate-spin" />
          <span className="ml-3 text-gray-500 text-sm">Verguenstigungen werden geladen...</span>
        </div>
      )}
    </div>
  );
}

/**
 * Hook to trigger Sovendus at the right moments
 */
export function useSovendusTrigger() {
  const [showSovendus, setShowSovendus] = useState(false);
  const [triggerData, setTriggerData] = useState({});

  const trigger = (type, data = {}) => {
    setTriggerData({ trigger: type, ...data });
    setShowSovendus(true);
  };

  const close = () => {
    setShowSovendus(false);
    setTriggerData({});
  };

  return { showSovendus, triggerData, trigger, close };
}
